server:
  port: 9811
spring:
  application:
    name: adminserver
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:9876/eureka/
security:
  basic:
    enabled: false
