server:
  port: 9807
spring:
  application:
    name: gateway
  zipkin:
      base-url: http://localhost:9812
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9876/eureka/
  instance:
    hostname: 127.0.0.1
