server:
  port: 9807
spring:
  application:
    name: consumer2
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:9876/eureka/

feign:
  hystrix:
   enabled: true
