server:
  port: 9801
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:example
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: provider-user
  zipkin:
    base-url: http://localhost:9812
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:9876/eureka/