server:
  port: 9802
spring:
  application:
    name: cunsumer
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:9876/eureka/
  instance:
   preferIpAddress: true

feign:
  hystrix:
   enabled: true
