server:
  port: 9802
spring:
  application:
    name: consumer
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:9876/eureka/
  zipkin:
      base-url: http://localhost:9812
  sleuth:
    sampler:
      percentage: 1.0
feign:
  hystrix:
   enabled: true
